<table>
    <tr><td align="right" style="background-color:#ffffff;">
        <img src="../images/logo.jpg" width="20%" align="right">
    </td></tr>
    <tr><td align="right" style="color:#777777;background-color:#ffffff;font-size:12px;">
        Abuzer Yakaryilmaz | April 03, 2019 (updated) 
    </td></tr>
    <tr><td align="right" style="color:#bbbbbb;background-color:#ffffff;font-size:11px;font-style:italic;">
        This cell contains some macros. If there is a problem with displaying mathematical formulas, please run this cell to load these macros.
    </td></tr>
</table>
$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\vhadamardzero}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\vhadamardone}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $

<h2> Matrices: Tensor Product</h2>

Tensor product is defined between any two matrices. The result is a new bigger matrix.

Before giving its formal definition, we define it based on examples.

Let's start with a simple case.

<i>A vector is also a matrix. Therefore, tensor product can be defined between two vectors or between one vector and one matrix.</i>

<h3> Tensor product of two vectors </h3>

We have two vectors: $ u = \myrvector{-2\\3} $ and $ v = \myrvector{1 \\ 2 \\ -3} $.

The tensor product of $u$ and $ v $ is denoted by $ u \otimes v $.

We may consider the tensor product as extending $ u $ by $ v $:

$$
    u \otimes v =  \myrvector{-2\\3} \otimes \myrvector{1 \\ 2 \\ -3} =
   \myrvector{ -2 \cdot  \myrvector{1 \\ 2 \\ -3} \\ 3 \cdot  \myrvector{1 \\ 2 \\ -3} } =
   \myrvector{ -2 \\ -4 \\ 6 \\ 3 \\ 6 \\ -9 }.
$$

Here, $ -2 $ in $ u $ is replaced with the vector $ (-2 \cdot v) $, and $ 3 $ in $ u $ is replaced with the vector $ 3 v $.

Thus each entry of $ u $ is replaced by a 3-dimensional vector, and the dimension of the result vector is $ 6~(=2 \cdot 3) $.

Algorithmically, each element in $ u $ is replaced by the multiplication of this element with the vector $ v $.

Let's find $ v \otimes u $ in Python.

In [1]:
# vector v
v = [1,2,-3]
# vector u
u=[-2,3]

vu = []

for i in range(len(v)): # Each element of v will be replaced
    for j in range(len(u)): # the vector u will come here after multiplying with the entry there
        vu.append( v[i] * u[j] )

print("v=",v)
print("u=",u)
print("vu=",vu)

v= [1, 2, -3]
u= [-2, 3]
vu= [-2, 3, -4, 6, 6, -9]


<h3> Task 1 </h3>

Find $ u \otimes v $ and $ v \otimes u $ for the given vectors $ u = \myrvector{-2 \\ -1 \\ 0 \\ 1} $ and $ v = \myrvector{ 1 \\ 2 \\ 3 } $.

In [8]:
#
# your solution is here
#
import numpy as np
u = [-2, -1, 0, 1]
v = [1, 2, 3]
uv = np.tensordot(np.array(u), np.array(v), axes = 0)

print("uv: " +  str(uv))

uv: [[-2 -4 -6]
 [-1 -2 -3]
 [ 0  0  0]
 [ 1  2  3]]


<a href="Math32_Tensor_Product_Solutions.ipynb#task1">click for our solution</a>

<b> Note:</b>

Tensor products are useful when we have a system composed by two (or more) sub-systems. 

Any new entry after tensoring represents a pair of entries, each of which comes from one of the sub-sytems.

We will see the usage of tensor products in the main tutorial.

<h3> Tensor product of two matrices </h3>

The definition is the same.

Let's find $ M \otimes N $ and $ N \otimes M $ for the given matrices
$
    M = \mymatrix{rrr}{-1 & 0 & 1 \\ -2 & -1 & 2 \\ 1 & 2 & -2} ~~\mbox{and}~~ 
    N = \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0}.
$

$ M \otimes N $: Each element of $ M $ will be replaced with the whole matrix $ N $ after multiplying with this element.

$$
    M \otimes N =
    \mymatrix{rrr}{-1 & 0 & 1 \\ -2 & -1 & 2 \\ 1 & 2 & -2} \otimes \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0}
    =
    \mymatrix{rrr}{ -1 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & 0 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & 1 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} \\
    -2 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & -1 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & 2 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} \\
    1 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & 2 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & -2 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0}}
$$

It is a boring task because of repetitions. 

Let us do this once by hand (in mind), and then check the result by Python.

$$
    M \otimes N = \mymatrix{rrrrrrrrr}{
        0 & -2 & -1 & 0 & 0 & 0 & 0 & 2 & 1 \\
        -3 & 1 & 2 & 0 & 0 & 0 & 3 & -1 & -2 \\
        1 & -1 & 0 & 0 & 0 & 0 & -1 & 1 & 0 \\
        0 & -4 & -2 & 0 & -2 & -1 & 0 & 4 & 2 \\
        -6 & 2 & 4 & -3 & 1 & 2 & 6 & -2 & -4 \\
        2 & -2 & 0 & 1 & -1 & 0 & -2 & 2 & 0 \\
        2 & 1 & 0 & 1 & -1 & 0 & -2 & 2 & 0 \\
        0 & 2 & 1 & 0 & 4 & 2 & 0 &  -4 & -2 \\
        3 & -1 & -2 & 6 & -2 & -4 & -6 & 2 & 4 \\
        -1 & 1 & 0 & -2 & 2 & 0 & 2 & -2 & 0
    }
$$

Now, let's find the same matrix in Python.

This time we will use four nested for-loops.

In [9]:
# matrix M
M = [ 
    [-1,0,1],
    [-2,-1,2],
    [1,2,-2]
]

# matrix N
N = [
    [0,2,1],
    [3,-1,-2],
    [-1,1,0]
]

# MN will be a (9x9)-dimensional matrix
# let's prepare it as a zero matrix
# this helps us to easily fill it 
MN=[]
for i in range(9):
    MN.append([])
    for j in range(9):
        MN[i].append(0)

for i in range(3): # row of M
    for j in range(3): # column of M
        for k in range(3): # row of N
            for l in range(3): # column of N
                MN[i*3+k][3*j+l] = M[i][j] * N[k][l] 

print("M-tensor-N is")                
for i in range(9):
    print(MN[i])

M-tensor-N is
[0, -2, -1, 0, 0, 0, 0, 2, 1]
[-3, 1, 2, 0, 0, 0, 3, -1, -2]
[1, -1, 0, 0, 0, 0, -1, 1, 0]
[0, -4, -2, 0, -2, -1, 0, 4, 2]
[-6, 2, 4, -3, 1, 2, 6, -2, -4]
[2, -2, 0, 1, -1, 0, -2, 2, 0]
[0, 2, 1, 0, 4, 2, 0, -4, -2]
[3, -1, -2, 6, -2, -4, -6, 2, 4]
[-1, 1, 0, -2, 2, 0, 2, -2, 0]


Let's find $ N \otimes M $ in Python.

We use the same code by interchanging $ N $ and $ M $.

In [10]:
# matrices M and N were defined above

# matrix NM will be prepared as a (9x9)-dimensional zero matrix
NM=[]
for i in range(9):
    NM.append([])
    for j in range(9):
        NM[i].append(0)

for i in range(3): # row of N
    for j in range(3): # column of N
        for k in range(3): # row of M
            for l in range(3): # column of M
                NM[i*3+k][3*j+l] = N[i][j] * M[k][l] 

print("N-tensor-M is")
for i in range(9):
    print(NM[i])

N-tensor-M is
[0, 0, 0, -2, 0, 2, -1, 0, 1]
[0, 0, 0, -4, -2, 4, -2, -1, 2]
[0, 0, 0, 2, 4, -4, 1, 2, -2]
[-3, 0, 3, 1, 0, -1, 2, 0, -2]
[-6, -3, 6, 2, 1, -2, 4, 2, -4]
[3, 6, -6, -1, -2, 2, -2, -4, 4]
[1, 0, -1, -1, 0, 1, 0, 0, 0]
[2, 1, -2, -2, -1, 2, 0, 0, 0]
[-1, -2, 2, 1, 2, -2, 0, 0, 0]


<h3> Task 2 </h3>

Find $ A \otimes B $ for the given matrices
$
    A = \mymatrix{rrr}{-1 & 0 & 1 \\ -2 & -1 & 2} ~~\mbox{and}~~ 
    B = \mymatrix{rr}{0 & 2 \\ 3 & -1 \\ -1 & 1 }.
$

In [12]:
#
# your solution is here
#
A = [
    [-1,0,1],
    [-2,-1,2]
]

B = [
    [0,2],
    [3,-1],
    [-1,1]
]

print("A =")
for i in range(len(A)):
    print(A[i])

print() # print a line
print("B =")
for i in range(len(B)):
    print(B[i])

# let's define A-tensor-B as a (6x6)-dimensional zero matrix
AB = []
for i in range(6):
    AB.append([])
    for j in range(6):
        AB[i].append(0)

    
        
# let's find A-tensor-B
for i in range(2):
    for j in range(3):
        # for each A(i,j) we execute the following codes
        a = A[i][j]
        # we access each element of B
        for m in range(3):
            for n in range(2):
                b = B[m][n]
                # now we put (a*b) in the appropriate index of AB
                AB[3*i+m][2*j+n] = a * b
    
    

print() # print a line
print("A-tensor-B =") 
print() # print a line
for i in range(6):
    print(AB[i])

A =
[-1, 0, 1]
[-2, -1, 2]

B =
[0, 2]
[3, -1]
[-1, 1]

A-tensor-B =

[0, -2, 0, 0, 0, 2]
[-3, 1, 0, 0, 3, -1]
[1, -1, 0, 0, -1, 1]
[0, -4, 0, -2, 0, 4]
[-6, 2, -3, 1, 6, -2]
[2, -2, 1, -1, -2, 2]


<a href="Math32_Tensor_Product_Solutions.ipynb#task2">click for our solution</a>

<h3> Task 3 </h3>

Find $ B \otimes A $ for the given matrices
$
    A = \mymatrix{rrr}{-1 & 0 & 1 \\ -2 & -1 & 2} ~~\mbox{and}~~ 
    B = \mymatrix{rr}{0 & 2 \\ 3 & -1 \\ -1 & 1 }.
$

You can use the code in your (our) solution for Task 2.

But please be careful with the indices and range values, and how they are interchanged (!)

In [11]:
#
# your solution is here
#
A = [
    [-1,0,1],
    [-2,-1,2]
]

B = [
    [0,2],
    [3,-1],
    [-1,1]
]

print() # print a line
print("B =")
for i in range(len(B)):
    print(B[i])
    
print("A =")
for i in range(len(A)):
    print(A[i])

# let's define B-tensor-A as a (6x6)-dimensional zero matrix
BA = []
for i in range(6):
    BA.append([])
    for j in range(6):
        BA[i].append(0)
        
# let's find B-tensor-A
for i in range(3):
    for j in range(2):
        # for each B(i,j) we execute the following codes
        b = B[i][j]
        # we access each element of A
        for m in range(2):
            for n in range(3):
                a = A[m][n]
                # now we put (a*b) in the appropriate index of AB
                BA[2*i+m][3*j+n] = b * a
    
    

print() # print a line
print("B-tensor-A =") 
print() # print a line
for i in range(6):
    print(BA[i])



B =
[0, 2]
[3, -1]
[-1, 1]
A =
[-1, 0, 1]
[-2, -1, 2]

B-tensor-A =

[0, 0, 0, -2, 0, 2]
[0, 0, 0, -4, -2, 4]
[-3, 0, 3, 1, 0, -1]
[-6, -3, 6, 2, 1, -2]
[1, 0, -1, -1, 0, 1]
[2, 1, -2, -2, -1, 2]


<a href="Math32_Tensor_Product_Solutions.ipynb#task3">click for our solution</a>